### PR TITLE
Licensing: Add no/custom license to enum

### LINKED ISSUE #448: Licensing: restricted datasets should have a license selector displayed
**Describe the bug**
Like with an open dataset, there should be a license selector here.

Image

Additionally, there is no option to not select a license - this should also be changed. 

**Is this a regression?**
No.

**Expected behavior**
Licenese selector should be in the restricted section and it should be possible to select no license.

**Screenshots**

**Environment**

- Damap version 4.5.0

### PR DESCRIPTION
**Pull request by BlueTechie**
## Description

Bugfix
#### What does this PR do?

Added enum values corresponding to "no license" and "custom license" for the licenses of datasets.

#### Dependencies

Depends on: https://github.com/tuwien-csd/damap-frontend/pull/449
Related to frontend issue: https://github.com/tuwien-csd/damap-frontend/issues/448
closes GH-

### CODE REVIEW

**Comment by ValentinFutterer** [comment]
It works pretty well - but in the export, no license and custom license is shown as a link, without a URL linked.
image

File: src/main/java/org/damap/base/enums/ELicense.java [hunk 1]
```diff
@@ -132,7 +132,9 @@ public enum ELicense {
   PDDL(
       "PDDL-1.0",
       "Open Data Commons Public Domain Dedication and License",
-      "https://spdx.org/licenses/PDDL-1.0");
+      "https://spdx.org/licenses/PDDL-1.0"),
+  NOLICENSE("NO-LICENSE", "No License", ""),
+  CUSTOM("CUSTOM-LICENSE", "Custom License", "");
```
Comment (ghost) [inline src/main/java/org/damap/base/enums/ELicense.java]: It seems that these identifiers mirror the SPDX identifiers. If that is the case, this should read `LicenseRef-UNLICENSED` or `LicenseRef-AllRightsReserved`, see [the SPDX spec](https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/).

```suggestion
  NOLICENSE("LicenseRef-AllRightsReserved", "All Rights Reserved", ""),
  CUSTOM("LicenseRef-Proprietary", "Custom License", "");
```

**Review by ValentinFutterer — APPROVED** [review]
Good work!
